// @koala-prepend "vendor/jquery-2.2.0.min.js"
// @koala-prepend "vendor/bootstrap.min.js"
// @koala-prepend "vendor/angular.min.js"
// @koala-prepend "vendor/angular-route.min.js"
// @koala-prepend "vendor/ui-bootstrap-tpls.min.js"
// @koala-prepend "vendor/moment.min.js"
// @koala-prepend "produce.js"