window.gtProduce = {
    beans_pole: {
        label           : "Beans, Pole (Vertical)",
        startType       : 'Either',
        hardiness       : 'Frost-Sensitive',
        spacing         : 2,
        rowsPerBed      : 1,
        seedDepth       : 0.5,
        yield           : 180,
        yieldType       : 'lbs',
        numPlants       : 180,
        plantHeight     : 84,
        plantInside     : -2,
        plantOutside    : 0,
        maturity        : 75,
        harvest         : 16,
        vertical        : true
    },
    beans_bush: {
        label           : "Beans, Bush",
        startType       : 'Either',
        hardiness       : 'Frost-Sensitive',
        spacing         : 3,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 68,
        yieldType       : 'lbs',
        numPlants       : 240,
        plantHeight     : 20,
        plantInside     : -2,
        plantOutside    : 0,
        maturity        : 65,
        harvest         : 3,
        vertical        : false
    },
    beets: {
        label           : "Beets",
        startType       : 'Seed',
        hardiness       : 'Moderately-Hardy',
        spacing         : 2,
        rowsPerBed      : 2,
        seedDepth       : 0.25,
        yield           : 120,
        yieldType       : 'lbs',
        numPlants       : 362,
        plantHeight     : 12,
        plantInside     : false,
        plantOutside    : -2,
        maturity        : 55,
        harvest         : 20,
        vertical        : false
    },
    bell_pepper: {
        label           : "Bell Pepper",
        startType       : 'Seedling',
        hardiness       : 'Frost-Intolerant',
        spacing         : 12,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 310,
        yieldType       : 'peppers',
        numPlants       : 62,
        plantHeight     : 16,
        plantInside     : -7,
        plantOutside    : 2,
        maturity        : 85,
        harvest         : 12,
        vertical        : false
    },
    bell_pepper_flavorburst: {
       label: "Flavorburst",
       parent: "bell_pepper"
    },
    bell_pepper_ace: {
       label: "Ace",
       parent: "bell_pepper"
    },
    broccoli: {
        label           : "Broccoli",
        startType       : 'Seedling',
        hardiness       : 'Hardy',
        spacing         : 14,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 80,
        yieldType       : 'lbs',
        numPlants       : 52,
        plantHeight     : 20,
        plantInside     : -8,
        plantOutside    : -4,
        maturity        : 60,
        harvest         : 4,
        vertical        : false
    },
    broccoli_arcadia: {
        label: "Arcadia",
        //maturity: 63,
        parent: "broccoli"
    },
    broccoli_belstar: {
        label: "Belstar",
        //maturity: 66,
        parent: "broccoli"
    },
    brussel_sprouts: {
        label: "Brussel Sprouts",
        maturity: 90,
        seedling: 6,
        harvest: 4,
        spacing: 18,
        vertical: false,
        rowsPerBed: 1
    },
    cabbage: {
        label           : "Cabbage",
        startType       : 'Seedling',
        hardiness       : 'Hardy',
        spacing         : 12,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 150,
        yieldType       : 'lbs',
        numPlants       : 60,
        plantHeight     : 15,
        plantInside     : -8,
        plantOutside    : -4,
        maturity        : 60,
        harvest         : 2,
        vertical        : false
    },
    carrot: {
        label           : "Carrot",
        startType       : 'Seed',
        hardiness       : 'Moderately-Hardy',
        spacing         : 1,
        rowsPerBed      : 2,
        seedDepth       : 0.125,
        yield           : 90,
        yieldType       : 'lbs',
        numPlants       : 720,
        plantHeight     : 12,
        plantInside     : 0,
        plantOutside    : -2,
        maturity        : 75,
        harvest         : 16,
        vertical        : false
    },
    cauliflower: {
        label           : "Cauliflower",
        startType       : 'seedling',
        hardiness       : 'Hardy',
        spacing         : 14,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 100,
        yieldType       : 'lbs',
        numPlants       : 52,
        plantHeight     : 20,
        plantInside     : -8,
        plantOutside    : -4,
        maturity        : 65,
        harvest         : 4,
        vertical        : false
    },
    celery: {
        label           : "Celery",
        startType       : 'seedling',
        hardiness       : 'Moderately-Hardy',
        spacing         : 12,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 120,
        yieldType       : 'lbs',
        numPlants       : 62,
        plantHeight     : 18,
        plantInside     : -6,
        plantOutside    : -2,
        maturity        : 80,
        harvest         : 2,
        vertical        : false
    },
    corn: {
        label           : "Corn",
        startType       : 'Seed',
        hardiness       : 'Frost-Sensitive',
        spacing         : 8,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 115,
        yieldType       : 'ears',
        numPlants       : 92,
        plantHeight     : 72,
        plantInside     : false,
        plantOutside    : 0,
        maturity        : 65,
        harvest         : 2,
        vertical        : false
    },
    cucumber: {
        label: "Cucumber",
        startType       : 'Seedling',
        hardiness       : 'Frost-Intolerant',
        spacing         : 9,
        rowsPerBed      : 1,
        seedDepth       : 0.5,
        yield           : 410,
        yieldType       : 'lbs',
        numPlants       : 41,
        plantHeight     : 84,
        plantInside     : -1,
        plantOutside    : 2,
        maturity        : 60,
        harvest         : 4,
        vertical        : true
    },
    cucumber_diva: {
        label: "Diva",
        parent: "cucumber"
    },
    eggplant: {
        label           : "Eggplant",
        startType       : 'Seedling',
        hardiness       : 'Frost-Sensitive',
        spacing         : 9,
        rowsPerBed      : 1,
        seedDepth       : 0.5,
        yield           : 400,
        yieldType       : 'lbs',
        numPlants       : 41,
        plantHeight     : 72,
        plantInside     : -8,
        plantOutside    : 0,
        maturity        : 90,
        harvest         : 16,
        vertical        : true
    },
    lettuce: {
        label           : "Lettuce",
        startType       : 'Either',
        hardiness       : 'Hardy',
        spacing         : 12,
        rowsPerBed      : 2,
        seedDepth       : 0.125,
        yield           : 112,
        yieldType       : 'lbs',
        //numPlants       : 41,
        plantHeight     : 12,
        plantInside     : -7,
        plantOutside    : -4,
        maturity        : 55,
        harvest         : 6,
        vertical        : false
    },
    melon: {
        label           : 'Melon',
        startType       : 'Either',
        hardiness       : 'Frost-Intolerant',
        spacing         : 9,
        rowsPerBed      : 1,
        seedDepth       : 0.25,
        yield           : 246,
        yieldType       : 'lbs',
        numPlants       : 41,
        plantHeight     : 84,
        plantInside     : -1,
        plantOutside    : 2,
        maturity        : 85,
        harvest         : 8,
        vertical        : true
    },
    melon_earlichamp: {
        label: "Earlichamp Cantalope",
        maturity: 72,
        parent: "melon"
    },
    melon_diplomat: {
        label: "Diplomat Galia",
        maturity: 70,
        parent: "melon"
    },
    melon_serenade: {
        label: "Serenade Butterscotch",
        maturity: 80,
        parent: "melon"
    },
    melon_sapomiel: {
        label: "Sapomiel Piel Del Sapo",
        maturity: 80,
        parent: "melon"
    },
    onion: {
        label           : 'Onion',
        startType       : 'Either',
        hardiness       : 'Hardy',
        spacing         : 1,
        rowsPerBed      : 4,
        seedDepth       : 0.125,
        yield           : 144,
        yieldType       : 'bunches',
        numPlants       : 1440,
        plantHeight     : 12,
        plantInside     : -7,
        plantOutside    : -4,
        maturity        : 85,
        harvest         : 4,
        vertical        : false
    },
    peas: {
        label           : 'Peas, Bush',
        startType       : 'Either',
        hardiness       : 'Hardy',
        spacing         : 2,
        rowsPerBed      : 2,
        seedDepth       : 0.5,
        yield           : 90,
        yieldType       : 'lbs',
        numPlants       : 362,
        plantHeight     : 18,
        plantInside     : -7,
        plantOutside    : -4,
        maturity        : 60,
        harvest         : 3,
        vertical        : false
    },
    potato: {
        label: "Potato",
        startType       : 'Seed',
        hardiness       : 'Moderately-Hardy',
        spacing         : 8,
        rowsPerBed      : 2,
        seedDepth       : 1.5,
        yield           : 145,
        yieldType       : 'lbs',
        numPlants       : 92,
        plantHeight     : 16,
        plantInside     : -6,
        plantOutside    : -2,
        maturity        : 65,
        harvest         : 8,
        vertical        : false
    },
    potato_yukon_gold: {
        label: "Yukon Gold",
        maturity: 80,
        parent: "potato"
    },
    potato_kennebec: {
        label: "Kennebec",
        maturity: 100,
        parent: "potato"
    },
    pumpkin: {
        label: "Pumpkin",
        maturity: 100,
        seedling: 3,
        harvest: 4,
        spacing: 24,
        vertical: false,
        rowsPer: 1
    },
    radish: {
        label: "Radish",
        startType       : 'Seed',
        hardiness       : 'Hardy',
        spacing         : 1,
        rowsPerBed      : 2,
        seedDepth       : 0.125,
        yield           : 60,
        yieldType       : 'bunches',
        numPlants       : 722,
        plantHeight     : 8,
        plantInside     : false,
        plantOutside    : -4,
        maturity        : 25,
        harvest         : 3,
        vertical        : false
    },
    spinach: {
        label           : "Spinach",
        startType       : 'Either',
        hardiness       : 'Hardy',
        spacing         : 6,
        rowsPerBed      : 2,
        seedDepth       : .25,
        yield           : 46,
        yieldType       : 'lbs',
        numPlants       : 122,
        plantHeight     : 8,
        plantInside     : -7,
        plantOutside    : -4,
        maturity        : 45,
        harvest         : 4,
        vertical        : false
    },
    sweet_potato: {
        label           : "Sweet Potato",
        startType       : 'Slip',
        hardiness       : 'Frost-Intolerant',
        spacing         : 12,
        rowsPerBed      : 2,
        seedDepth       : 3,
        yield           : 600,
        yieldType       : 'lbs',
        numPlants       : 60,
        plantHeight     : 12,
        plantInside     : -2,
        plantOutside    : 6,
        maturity        : 120,
        harvest         : 1,
        vertical        : false
    },
    squash: {
        label: "Squash",
        startType       : 'either',
        hardiness       : 'Frost-Intolerant',
        spacing         : 9,
        rowsPerBed      : 1,
        seedDepth       : 0.5,
        yield           : 154,
        yieldType       : 'lbs',
        numPlants       : 41,
        plantHeight     : 84,
        plantInside     : -1,
        plantOutside    : 2,
        maturity        : 90,
        harvest         : 14,
        vertical        : true
    },
    squash_butternut: {
        label: "Waltham Butternut",
        maturity: 105,
        parent: "squash"
    },
    squash_butternut_butterscotch: {
        label: "Butterscotch PMR",
        maturity: 100,
        parent: "squash"
    },
    squash_acorn_honeybear: {
        label: "Honey Bear",
        maturity: 85,
        parent: "squash"
    },
    swiss_chard: {
        label: "Swiss Chard",
        maturity: 50,
        seedling: 4,
        harvest: 20,
        spacing: 12,
        vertical: false,
        rowsPer: 2
    },
    tomato: {
        label           : "Tomato",
        startType       : 'Either',
        hardiness       : 'Frost-Sensitive',
        spacing         : 24,
        rowsPerBed      : 1,
        seedDepth       : 0.25,
        yield           : 615,
        yieldType       : 'lbs',
        numPlants       : 41,
        plantHeight     : 84,
        plantInside     : -8,
        plantOutside    : 0,
        maturity        : 90,
        harvest         : 16,
        vertical        : true
    },
    tomato_big_beef: {
        label: "Big Beef",
        maturity: 70,
        parent: "tomato"
    },
    tomato_sun_gold: {
        label: "Sun Gold",
        maturity: 57,
        parent: "tomato"
    },
    tomato_black_cherry: {
        label: "Black Cherry",
        maturity: 64,
        parent: "tomato"
    },
    tomato_matts_wild_cherry: {
        label: "Matts Wild Cherry",
        maturity: 60,
        parent: "tomato"
    },
    tomato_supersweet_100: {
        label: "Supersweet 100",
        maturity: 60,
        parent: "tomato"
    },
    turnip: {
        label           : "Turnip",
        startType       : 'Seed',
        hardiness       : 'Moderately-Hardy',
        spacing         : 2,
        rowsPerBed      : 2,
        seedDepth       : 0.125,
        yield           : 120,
        yieldType       : 'lbs',
        numPlants       : 362,
        plantHeight     : 12,
        plantInside     : false,
        plantOutside    : -2,
        maturity        : 45,
        harvest         : 4,
        vertical        : true
    },
    watermelon: {
        label           : "Watermelon",
        startType       : 'Either',
        hardiness       : 'Frost-Intolerant',
        spacing         : 21,
        rowsPerBed      : 1,
        seedDepth       : 0.25,
        yield           : 320,
        yieldType       : 'lbs',
        numPlants       : 16,
        plantHeight     : 16,
        plantInside     : -2,
        plantOutside    : 2,
        maturity        : 90,
        harvest         : 3,
        vertical        : false
    }
};